// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { createUserFromDiscriminatorValue, deserializeIntoUser, serializeUser, type User } from '../../models/';
import { BaseRequestBuilder, HttpMethod, RequestInformation, type Parsable, type ParsableFactory, type RequestAdapter, type RequestConfiguration, type RequestOption } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /user/createWithList
 */
export class CreateWithListRequestBuilder extends BaseRequestBuilder<CreateWithListRequestBuilder> {
    /**
     * Instantiates a new CreateWithListRequestBuilder and sets the default values.
     * @param pathParameters The raw url or the Url template parameters for the request.
     * @param requestAdapter The request adapter to use to execute the requests.
     */
    public constructor(pathParameters: Record<string, unknown> | string | undefined, requestAdapter: RequestAdapter) {
        super(pathParameters, requestAdapter, "{+baseurl}/user/createWithList", (x, y) => new CreateWithListRequestBuilder(x, y));
    }
    /**
     * Creates list of users with given input array
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of User
     */
    public post(body: User[], requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<User | undefined> {
        const requestInfo = this.toPostRequestInformation(
            body, requestConfiguration
        );
        return this.requestAdapter.sendAsync<User>(requestInfo, createUserFromDiscriminatorValue, undefined);
    }
    /**
     * Creates list of users with given input array
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
    public toPostRequestInformation(body: User[], requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation {
        if(!body) throw new Error("body cannot be undefined");
        const requestInfo = new RequestInformation(HttpMethod.POST, this.urlTemplate, this.pathParameters);
        requestInfo.configure(requestConfiguration);
        requestInfo.headers.tryAdd("Accept", "application/json");
        requestInfo.setContentFromParsable(this.requestAdapter, "application/json", body, serializeUser);
        return requestInfo;
    }
}
// tslint:enable
// eslint-enable
