// tslint:disable
// eslint-disable
// Generated by Microsoft Kiota
import { InventoryRequestBuilder } from './inventory/';
import { OrderRequestBuilder } from './order/';
import { BaseRequestBuilder, type RequestAdapter } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /store
 */
export class StoreRequestBuilder extends BaseRequestBuilder<StoreRequestBuilder> {
    /**
     * The inventory property
     */
    public get inventory(): InventoryRequestBuilder {
        return new InventoryRequestBuilder(this.pathParameters, this.requestAdapter);
    }
    /**
     * The order property
     */
    public get order(): OrderRequestBuilder {
        return new OrderRequestBuilder(this.pathParameters, this.requestAdapter);
    }
    /**
     * Instantiates a new StoreRequestBuilder and sets the default values.
     * @param pathParameters The raw url or the Url template parameters for the request.
     * @param requestAdapter The request adapter to use to execute the requests.
     */
    public constructor(pathParameters: Record<string, unknown> | string | undefined, requestAdapter: RequestAdapter) {
        super(pathParameters, requestAdapter, "{+baseurl}/store", (x, y) => new StoreRequestBuilder(x, y));
    }
}
// tslint:enable
// eslint-enable
